#!/bin/sh
#
# Tomcat Server
#
# chkconfig: 2345 96 30
# description: Java servlet container

# Source function library.
#. /etc/init.d/functions

USER=`whoami`
RUN_AS_USER=spider # Adjust run user here
CATALINA_HOME=/opt/tomcat/tomcat-dev

if [ `whoami` != 'root' ] && [ `whoami` != 'spider' ] ; then
        echo "ERROR: This command needs to be run as root user, or spider user. You are: `whoami`"
        exit 1;
fi


start() {
        echo "Starting Tomcat: "
        if [ "x$USER" != "x$RUN_AS_USER" ]; then
          su - $RUN_AS_USER -c "$CATALINA_HOME/bin/startup.sh"
        else
          $CATALINA_HOME/bin/startup.sh
        fi
        echo "done."
}
stop() {
        echo "Shutting down Tomcat: "
        if [ "x$USER" != "x$RUN_AS_USER" ]; then
          su - $RUN_AS_USER -c "$CATALINA_HOME/bin/shutdown.sh -force"
        else
          $CATALINA_HOME/bin/shutdown.sh -force
        fi
        PID=`ps -ef | grep $CATALINA_HOME | grep java | grep -v grep | awk '{print $2}'`
        if [ "$PID" != "" ]; then
                for INDEX in {1..5}
                do
                        sleep 5;
                        PID=`ps -ef | grep $CATALINA_HOME | grep java | grep -v grep | awk '{print $2}'`
                        if [ "$PID" != "" ]; then
                                echo -n "${INDEX}."
                        else
                                break;
                        fi
                done
                echo ""
                if [ "$PID" != "" ]; then
                        echo "ERROR: Cannot stop tomcat naturally. Killing..."
                        echo "# kill -9 $PID"
                        kill -9 $PID
                        PID=`ps -ef | grep $CATALINA_HOME | grep java | grep -v grep | awk '{print $2}'`
                        if [ "$PID" != "" ]; then
                                echo "ERROR: Trouble stopping tomcat. PID=$PID"
                                exit 1;
                        else
                                echo "# Tomcat process stopped successfully"
                        fi
                else
                        echo "# Tomcat process stopped successfully"
                fi
        fi
        echo "done."
}
status() {
        PID=`ps -ef | grep $CATALINA_HOME | grep java | grep -v grep | awk '{print $2}'`
        if [ "$PID" != "" ]; then
                echo "Tomcat is running. PID=$PID"
        else
                echo "Tomcat is down"
        fi
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        sleep 10
        start
        ;;
  status)
        status
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|status}"
esac

exit 0

